Remove support for qmake and change everything to cmake

diff --git a/kdiff3/configure b/kdiff3/configure
--- a/kdiff3/configure
+++ b/kdiff3/configure
@@ -2,7 +2,7 @@
 # Manually created configure
 
 function showUsage {
-   printf "Usage: %s: [-d] [-o directory] [kde4|qt4] \n" $0
+   printf "Usage: %s: [-d] [-o directory] [kde4|qt4|qt5] \n" $0
    echo Example 1: $0 kde4
    echo Example 2: $0 -d qt4
    echo Options:
@@ -13,11 +13,12 @@ function showUsage {
    exit 2
 }
 
-echo "configure for KDiff3 Qt4/KDE4 by Joachim Eibl"
+echo "configure for KDiff3 Qt4/Qt5/KDE4"
 
 config=release
 outputDir=""
 currentDir=`pwd`
+prefix="/usr"
 
 while getopts do: flag
 do
@@ -27,6 +28,7 @@ do
     ?)   showUsage;;
     esac
 done
+
 if [ ! -z "$debug" ]; then
     printf "Option -d specified\n"
 fi
@@ -34,54 +36,61 @@ fi
 shift $(($OPTIND - 1))
 #printf "Remaining arguments are: %s\n" "$*"
 
+buildDir=""
+build=""
 
-if [ "$1" = "kde4" ]; then
-   if [ "$outputDir" = "" ]; then
-      outputDir="${config}Kde"
-   fi
-   echo Trying to build for KDE4. If anything fails see the README for details.
-   echo Creating and entering subdir "$outputDir"
-   mkdir "$outputDir"                                  # create sub directory
-   cd "$outputDir"
-   export QT_SELECT=4
-   echo "Running cmake \"$currentDir\" -DCMAKE_INSTALL_PREFIX=`kde4-config --prefix`"
-   if [ config = "debug" ]; then
-     cmake "$currentDir" -DCMAKE_INSTALL_PREFIX=`kde4-config --prefix` -DCMAKE_BUILD_TYPE=debugfull
-   else
-     cmake "$currentDir" -DCMAKE_INSTALL_PREFIX=`kde4-config --prefix` 
-   fi
-   if [ $? -ne 0 ]
-   then
-      echo "CMake errors."
-      exit
-   fi
+case "$1" in
+    "kde4")
+        buildDir="${config}Kde"
+        build="KDE4"
+        prefix="`kde4-config --prefix`"
+        export QT_SELECT=4
+        ;;
+    "qt4")
+        buildDir="${config}Qt4"
+        build="Qt4"
+        ;;
+    "qt5")
+        buildDir="${config}Qt5"
+        build="Qt5"
+        ;;
+    *)
+        showUsage
+        ;;
+esac
 
-   echo Running make.
-   make                                           # run make (compile and link)
-   if [ $? -ne 0 ]
-   then
-      echo "Compile errors."
-      exit
-   fi
 
-   echo If everything went OK then KDiff3 was built in the subdir "$outputDir".
-   echo "Install as root (requires password)."
-   sudo make install                              # install as root user
-elif [ "$1" = "qt4" ]; then
-   if [ "$outputDir" = "" ]; then
-      outputDir="${config}Qt"
-   fi
-   echo Trying to build for Qt4 without KDE
-   echo Creating and entering subdir "$outputDir"
-   mkdir "$outputDir"                                  # create sub directory
-   cd "$outputDir"
-   qmakecmd="qmake CONFIG+=$config \"$currentDir/src-QT4/kdiff3.pro\""
-   echo "Running $qmakecmd"
-   $qmakecmd
-   echo "Running make"
-   make
-   echo "If everything went OK then KDiff3 was built as $outputDir/kdiff3"
-else
-   showUsage
+if [ "${outputDir}" = "" ]; then
+    outputDir="${buildDir}"
 fi
+
+echo Trying to build for ${build}. If anything fails see the README for details.
+echo Creating and entering subdir "$outputDir"
+mkdir "$outputDir"                              # create sub directory
+cd "$outputDir"
+
+echo "Running cmake \"$currentDir\" -DCMAKE_INSTALL_PREFIX=${prefix} -DBUILD_WITH=${build}"
+if [ config = "debug" ]; then
+    cmake "$currentDir" -DCMAKE_INSTALL_PREFIX="${prefix}" -DCMAKE_BUILD_TYPE=debugfull -DBUILD_WITH="${build}"
+else
+    cmake "$currentDir" -DCMAKE_INSTALL_PREFIX="${prefix}" -DCMAKE_BUILD_TYPE=Release -DBUILD_WITH="${build}"
+fi
+
+if [ $? -ne 0 ]
+then
+    echo "CMake errors."
+    exit
+fi
+
+echo Running make.
+make -j                                         # run make (compile and link)
+if [ $? -ne 0 ]
+then
+    echo "Compile errors."
+    exit
+fi
+
+echo If everything went OK then KDiff3 was built in the subdir "$outputDir".
+echo "Install as root (requires password)."
+sudo make install                              # install as root user
 
